### ISSUE TITLE
Wrong attribute reference parsing for Enterprise User and Custom schemas

### ISSUE THREAD

**Issue by andrea-patricelli** [apache/directory-scimple#704]
Applying a patch like this

```
PATCH http://localhost:8080/v2/Users/43e99ad1-849a-486c-aa50-08a5728ec3c7
Content-Type: application/scim+json
Accept: application/json
```

``` json

{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "replace",
      "path": "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.employeeNumber",
      "value": "56789"
    },
    {
      "op": "add",
      "path": "emails",
      "value": [
        {
          "value": "updated_ee026d943-4143-4043-8ef1-88994ef59ec41bc8cdd7-e@email.com",
          "type": "work"
        }
      ]
    },
    {
      "op": "replace",
      "path": "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.manager",
      "value": {
        "value": "bulkId:asdsdfas"
      }
    },
    {
      "op": "add",
      "path": "phoneNumbers",
      "value": [
        {
          "value": "123456789",
          "type": "home"
        }
      ]
    },
    {
      "op": "replace",
      "path": "name.familyName",
      "value": "updated_Family name"
    },
    {
      "op": "replace",
      "path": "urn:mem:params:scim:schemas:extension:LuckyNumberExtension.luckyNumber",
      "value": "12345"
    },
    {
      "op": "replace",
      "path": "password",
      "value": "Password-0101"
    }
  ]
}
```

Results into this error

```
java.lang.NullPointerException: Cannot invoke "org.apache.directory.scim.spec.schema.Schema.getAttribute(String)" because "schema" is null
	at org.apache.directory.scim.core.repository.DefaultPatchHandler.apply(DefaultPatchHandler.java:135) ~[scim-core-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.apache.directory.scim.core.repository.DefaultPatchHandler.apply(DefaultPatchHandler.java:118) ~[scim-core-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.apache.directory.scim.example.spring.service.InMemoryUserService.patch(InMemoryUserService.java:195) ~[classes/:na]
	at org.apache.directory.scim.example.spring.service.InMemoryUserService.patch(InMemoryUserService.java:59) ~[classes/:na]
	at org.apache.directory.scim.server.rest.BaseResourceTypeResourceImpl.lambda$patch$1(BaseResourceTypeResourceImpl.java:265) ~[scim-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.apache.directory.scim.server.rest.BaseResourceTypeResourceImpl.update(BaseResourceTypeResourceImpl.java:286) ~[scim-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.apache.directory.scim.server.rest.BaseResourceTypeResourceImpl.patch(BaseResourceTypeResourceImpl.java:264) ~[scim-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
```

This because seems that [AttributeReference](https://github.com/apache/directory-scimple/blob/develop/scim-spec/scim-spec-schema/src/main/java/org/apache/directory/scim/spec/filter/attribute/AttributeReference.java) is only supporting notation with colon istead of dot, e.g.  `urn:mem:params:scim:schemas:extension:LuckyNumberExtension:luckyNumber` and `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:employeeNumber`.

Is this a bug or a feature?

**Comment by bdemers** [comment]
See section [`3.10` of the SCIM Protocol RFC](https://datatracker.ietf.org/doc/html/rfc7644#section-3.10)

> For example, the attribute 'age' defined in "urn:ietf:params:scim:schemas:exampleCo:2.0:hr" is uniquely identified as "urn:ietf:params:scim:schemas:exampleCo:2.0:hr:age". Complex attributes' sub-attributes are referenced via nested dot ('.') notation, i.e., {urn}:{Attribute name}.{Sub-Attribute name}.

So in your example your attribute path of `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.manager` should be `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:manager` (or simply `manager`).

(NOTE: this notation creates some interesting parsing issues when figuring out of a URN is a schema or an attribute, but... this is what is defined in the spec).

If you think we are miss-interrupting the spec, please comment and let us know and we can continue the discussion!

**Comment by andrea-patricelli** [comment]
According to the attached spec it is definitely not a bug.
Unfortunately there are some SCIM implementations that do not comply with that spec and this lead us to make confusion.

Thanks a lot for the feedback @bdemers and merry Christmas!

**Comment by bdemers** [comment]
@andrea-patricelli 
If you can point us to docs or examples of specific issues with vendors we can try to:
- Contact the vendor
- Add some sort of quarks work around, no ideal, but if it's a popular vendor it might be something we would want to support.

Merry Christmas to you too!
